### ISSUE TITLE
“今日音樂”問題

### ISSUE THREAD

**Issue by kinosang** [sanddudu/nextday-desktop#3]
Mac OS X 系統下，播放音樂出現：

Uncaught node.js Error

Error: An attempt was made to use an object that is not, or is no longer, usable.
    at T (file:///var/folders/j4/2rpf1szj02j9zwfy3gt9my_r0000gn/T/.org.chromium.Chromium.VUhZIO/js/audioplayer.min.js:6:2555)
    at HTMLDivElement.eval (file:///var/folders/j4/2rpf1szj02j9zwfy3gt9my_r0000gn/T/.org.chromium.Chromium.VUhZIO/js/audioplayer.min.js:6:3665)
    at HTMLDivElement.o.event.dispatch (file:///var/folders/j4/2rpf1szj02j9zwfy3gt9my_r0000gn/T/.org.chromium.Chromium.VUhZIO/js/jquery-2.1.0.min.js:3:6055)
    at HTMLDivElement.r.handle (file:///var/folders/j4/2rpf1szj02j9zwfy3gt9my_r0000gn/T/.org.chromium.Chromium.VUhZIO/js/jquery-2.1.0.min.js:3:2830)

**Comment by sanddudu** [comment]
由于你是自行封装，我无法复现该问题

请确保：
node-webkit 版本为 0.6.0
使用的 ffmpeg 库为 Chromium 28.0.1500.11 的 ffmepg 库。原版附带的库不支持 mp3 播放。
